apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-service
  name: redis-service
  namespace: db
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 30893 
  selector:
    app: redis
  type: NodePort